<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title','url','body','excerpt','published_at','category_id'
    ];
    protected $dates = ['published_at'];

    protected $appends = ['published_date'];

    public function getRouteKeyName()
    {
        return 'url'; // TODO: Change the autogenerated stub
    }

    //
    public function category() // $post->category->name
    {
        //retonarme este post-> que pertenece a una categoria
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {   //Pertenece a muchos
        return $this->belongsToMany(Tag::class);

    }

    /**
     * @param $query
     */
    public function scopePublished($query){
       $query->whereNotNull('published_at')
           ->where('published_at', '<=', Date('Y-m-d H:i:s'))
           ->latest('published_at');

    }
}
